version: '3'
services:
    postgres:
      image: postgres:alpine
      container_name: remembrall-postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=remembrall
    php:
      image: klapuch/docker:fpm-project
      working_dir: /var/www/Remembrall
      volumes:
          - .:/var/www/Remembrall
          - ./sendmail:/usr/sbin/fake-sendmail
    server:
      image: nginx:alpine
      working_dir: /var/www/Remembrall
      volumes:
          - .:/var/www/Remembrall
          - ./site.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 8080:80
      depends_on:
        - postgres
        - php