version: '3'
services:
    postgres:
      image: postgres:alpine
      container_name: remembrall-postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=remembrall
      ports:
        - 5432:5432
    php:
      image: klapuch/docker:fpm-project
      volumes:
          - .:/var/www/Remembrall
          - ./sendmail:/usr/sbin/fake-sendmail
    server:
      image: nginx:alpine
      volumes:
          - .:/var/www/Remembrall
          - ./site.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80